SELECT * FROM "MEMBER" m 

CREATE TABLE "HR"."BBS" 
   (	"no" NUMBER(38,0), 
	"TITLE" VARCHAR2(100), 
	"CONTENT" VARCHAR2(100), 
	"WRITER" VARCHAR2(100), 
	 CONSTRAINT "BBS_PK" PRIMARY KEY ("no"))
	 
	 
SELECT * FROM BBS b 


CREATE TABLE "HR"."TEST10"(
	ID VARCHAR2(100),
	NAME VARCHAR2(100),
	PW VARCHAR2(100),
	TEL VARCHAR2(100)
)

SELECT * FROM TEST10 t 